# Generated by Django 2.2.12 on 2020-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monthly_replenishment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cash', models.BooleanField(default=False)),
                ('closed', models.NullBooleanField(default=False)),
                ('onetime_envelope', models.NullBooleanField(default=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'конверт',
                'verbose_name_plural': 'Конверты',
                'ordering': ['name', 'cash'],
            },
        ),
    ]
