# Generated by Django 2.2.12 on 2020-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0004_auto_20180828_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelopes',
            name='account',
        ),
    ]
