# Generated by Django 2.2.12 on 2020-04-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151110_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
    ]
