# Generated by Django 2.2.12 on 2020-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200415_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='account',
        ),
    ]
