# Generated by Django 2.2.12 on 2020-05-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envelopes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularMonthlyExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Постоянный месячный расход',
                'verbose_name_plural': 'Постоянные месячные расходы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envelopes.Envelopes')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-created_date', 'name'],
            },
        ),
    ]
