# Generated by Django 2.2.12 on 2020-04-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20151110_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-created_date', 'name'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='regularmonthlyexpenses',
            options={'ordering': ['name'], 'verbose_name': 'Постоянный месячный расход', 'verbose_name_plural': 'Постоянные месячные расходы'},
        ),
    ]
